version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d:Z
    ports:
      - "5433:5432"
    env_file:
      - ./db.env
    networks:
      - em_network
  
  products-service:
    build:
      context: ./services/products/
      dockerfile: Dockerfile
    container_name: products-service
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./services/products:/app:z
    user: root
    networks:
      - em_network

  history-service:
    build:
      context: ./services/history/
      dockerfile: Dockerfile
    container_name: history-service
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./services/history:/app:z
    user: root
    networks:
      - em_network

networks:
  em_network:

volumes:
  db_init:
