version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d:Z
    ports:
      - "5433:5432"
    env_file:
      - ./db.env
  
volumes:
  db_init:
